### ISSUE TITLE
Support obtain cam_position on Geotiff.crs directly

### ISSUE THREAD

**Issue by HowcanoeWang** [UTokyo-FieldPhenomics-Lab/EasyIDP#35]
I could replicate the error you mentioned here

```python
>>> import easyidp as idp
>>> lotus = idp.data.Lotus()
>>> ms = idp.Metashape(lotus.metashape.project, chunk_id=0) 
>>> ms._world2crs(ms._local2world(ms.photos[0].transform[0:3, 3])) 
array([139.54053245,  35.73458169, 130.09433649])
```
But if you changed the `ms.crs` to geotiff and then do the same thing:
```python
>>> import pyproj                                   
>>> ms.crs = pyproj.CRS.from_epsg(32654)              
>>> ms._world2crs(ms._local2world(ms.photos[0].transform[0:3, 3]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\OneDrive\Program\GitHub\EasyIDP\easyidp\metashape.py", line 99, in _world2crs
    return convert_proj3d(points_np, self.world_crs, self.crs)
  File "D:\OneDrive\Program\GitHub\EasyIDP\easyidp\metashape.py", line 1047, in convert_proj3d
    return out[0, :]
UnboundLocalError: local variable 'out' referenced before assignment
```

Temporary solution: 

Set `ms.crs = pyproj.from_epsg(4326)` first and then get photo location, and transform to GIS crs by 

```python
pos = {p.label: ms._world2crs(ms._local2world(p.transform[0:3, 3]))   for p in ms.photos}
transformer = pyproj.Transformer.from_proj(pyproj.from_epsg(4326), pyproj.from_epsg(32654))

out = {}
for k,v in pos.items():
    # here the lon and lat need to be reversed for pyproj package
    transformed = transformer.transform(v[1], v[0], v[2])
    out[k] = np.asarray(transformed).T
```

Detailed explanation:
Ths crs in the Metashape is created from photos' meta_info, often epsg4326 with lon and lat, and the software will "display" in this coords. 

> local -> world -> crs(photo_meta)

When you export outputs from Metashape, you can specify another CRS for geotiff (in this case is epsg:32654)

> local -> world -> crs(photo_meta) -> geotiff

Probably in the next release, the `ms.crs` -> `ms.photo_meta_crs`, and then `ms.crs` -> geotiff.crs

and you can get photo position at current geotiff crs by 
```python
>>> ms.get_photo_position(photos[0], crs=geotiff.crs)
array([[ 368030.75661044, 3955476.94877388, 129.8508284]])
```

_Originally posted by @HowcanoeWang in https://github.com/UTokyo-FieldPhenomics-Lab/EasyIDP/discussions/12#discussioncomment-3338434_

**Comment by HowcanoeWang** [comment]
Link point: 

1. compare camera to plot by angles #36 
2. adjust to pix4d cases (no such complicated conversion routine), `pix4d.photos[0].get_camera_center()` #37
