### ISSUE TITLE
Better notice if ROI has no z values

### ISSUE THREAD

**Issue by HowcanoeWang** [UTokyo-FieldPhenomics-Lab/EasyIDP#47]
```
import easyidp as idp
print(idp.__version__)

2.0.0.dev3

ms = idp.Metashape("/Users/benweinstein/Dropbox/Weecology/everglades_species/easyidp/Hidden_Little_03_24_2022.psx", chunk_id=0)
roi = idp.ROI("/Users/benweinstein/Dropbox/Weecology/everglades_species/easyidp/example_bird.shp") 
img_dict = roi.back2raw(ms)

[shp][proj] Use projection [WGS 84] for loaded shapefile [example_bird.shp]

[shp] read shp [example_bird.shp]:   0%|          | 0/1 [00:00<?, ?it/s]
[shp] read shp [example_bird.shp]: 100%|##########| 1/1 [00:00<00:00, 212.31it/s]Traceback (most recent call last):
  Python Shell, prompt 22, line 5
  File "/Users/benweinstein/.conda/envs/DeepTreeAttention/lib/python3.8/site-packages/easyidp/roi.py", line 401, in back2raw
    out_dict = recons.back2raw(self, **kwargs)
  File "/Users/benweinstein/.conda/envs/DeepTreeAttention/lib/python3.8/site-packages/easyidp/metashape.py", line 259, in back2raw
    save_path = None
  File "/Users/benweinstein/.conda/envs/DeepTreeAttention/lib/python3.8/site-packages/easyidp/metashape.py", line 209, in back2raw_crs
    local_coord = self._world2local(self._crs2world(points_xyz))
  File "/Users/benweinstein/.conda/envs/DeepTreeAttention/lib/python3.8/site-packages/easyidp/metashape.py", line 112, in _crs2world
    return convert_proj3d(points_np, self.crs, self.world_crs)
  File "/Users/benweinstein/.conda/envs/DeepTreeAttention/lib/python3.8/site-packages/easyidp/metashape.py", line 1110, in convert_proj3d
    out = np.vstack([lat_m, lon_m, alt_m]).T
builtins.IndexError: index 2 is out of bounds for axis 1 with size 2
```
Looks like we are missing the z dimension.

**Comment by HowcanoeWang** [comment]
Also, when DSM did not cover all ROI, will return 

[x, y, nan]

also need to notice
