### ISSUE TITLE
Fix numpy deprecates np.float data type

### ISSUE THREAD

**Issue by HowcanoeWang** [UTokyo-FieldPhenomics-Lab/EasyIDP#80]

**Comment by bw4sz** [comment]
I just found this error if its useful. 

```
import easyidp as idp
print(idp.__version__)
ms = idp.Metashape("/Users/benweinstein/Dropbox/Weecology/everglades_species/easyidp/Hidden_Little_03_24_2022.psx", chunk_id=0)

2.0.0.dev4

Traceback (most recent call last):
  Python Shell, prompt 4, line 3
    pass
  File "/Users/benweinstein/.conda/envs/BirdDetector/lib/python3.9/site-packages/easyidp/metashape.py", line 107, in __init__
    self.open_project(project_path, chunk_id)
  File "/Users/benweinstein/.conda/envs/BirdDetector/lib/python3.9/site-packages/easyidp/metashape.py", line 174, in open_project
    self.open_chunk(self.chunk_id)
  File "/Users/benweinstein/.conda/envs/BirdDetector/lib/python3.9/site-packages/easyidp/metashape.py", line 246, in open_chunk
    chunk_content_dict = read_chunk_zip(
  File "/Users/benweinstein/.conda/envs/BirdDetector/lib/python3.9/site-packages/easyidp/metashape.py", line 1145, in read_chunk_zip
    chunk_dict["transform"] = _decode_chunk_transform_tag(transform_tags[0])
  File "/Users/benweinstein/.conda/envs/BirdDetector/lib/python3.9/site-packages/easyidp/metashape.py", line 1284, in _decode_chunk_transform_tag
    transform.rotation = np.fromstring(chunk_rotation_str, sep=" ", dtype=np.float).reshape((3, 3))
  File "/Users/benweinstein/.conda/envs/BirdDetector/lib/python3.9/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
builtins.AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

```
import numpy as np
print(np.__version__)

1.24.2
```

What was the solution here?
